import Image1 from "@/assets/images/i1.png";
import Image2 from "@/assets/images/i2.png";
import Image3 from "@/assets/images/i3.png";
import Image4 from "@/assets/images/i4.png";
import Image5 from "@/assets/images/i5.png";
import Image6 from "@/assets/images/i6.png";

export const PLACEMENTS_DATA = [
  {
    id: 1,
    image: Image1,
    title: "Mid-Roll Ad – Tech Podcast",
    host: "Tech Talks Daily",
    verified: true,
    traffic: "50K Estimated Monthly Foot Traffic.",
    location: "United States",
    duration: "30 days",
    slots: "7 / 10 Slots Available (March)",
    price: 500,
    category: "Podcast",
    available: true,
    slotsPercentage: 70,
  },
  {
    id: 2,
    image: Image2,
    title: "Pre-Roll Video Ad – YouTube",
    host: "Tech Talks Daily",
    verified: true,
    traffic: "50K Estimated Monthly Foot Traffic.",
    location: "United States",
    duration: "30 days",
    slots: "Fully Booked (March)",
    price: 500,
    category: "Podcast",
    available: false,
    slotsPercentage: 0,
  },
  {
    id: 3,
    image: Image3,
    title: "Pre-Roll Video Ad – YouTube",
    host: "Tech Talks Daily",
    verified: true,
    traffic: "50K Estimated Monthly Foot Traffic.",
    location: "United States",
    duration: "30 days",
    slots: "Fully Booked (March)",
    price: 500,
    category: "Podcast",
    available: false,
    slotsPercentage: 0,
  },
  {
    id: 4,
    image: Image4,
    title: "Homepage Banner – Blog",
    host: "Tech Talks Daily",
    verified: true,
    traffic: "50K Estimated Monthly Foot Traffic.",
    location: "United States",
    duration: "30 days",
    slots: "7 / 10 Slots Available (March)",
    price: 500,
    category: "Blog",
    available: true,
    slotsPercentage: 70,
  },
  {
    id: 5,
    image: Image5,
    title: "Sidebar Placement – Industry S...",
    host: "Tech Talks Daily",
    verified: true,
    traffic: "50K Estimated Monthly Foot Traffic.",
    location: "United States",
    duration: "30 days",
    slots: "7 / 10 Slots Available (March)",
    price: 500,
    category: "Website",
    available: true,
    slotsPercentage: 70,
  },
  {
    id: 6,
    image: Image6,
    title: "Sponsored Post – Medium Publi...",
    host: "Tech Talks Daily",
    verified: true,
    traffic: "50K Estimated Monthly Foot Traffic.",
    location: "United States",
    duration: "30 days",
    slots: "7 / 10 Slots Available (March)",
    price: 500,
    category: "Website",
    available: true,
    slotsPercentage: 70,
  },
];
